# # Use a smaller base image
# FROM node:18-alpine as build

# # Set the working directory
# WORKDIR /web

# # Copy package.json and package-lock.json
# COPY package*.json ./

# # Install dependencies
# RUN npm install

# # Copy the rest of the application code
# COPY . .

# # Build the application
# RUN npm run build

# # Use an even smaller base image for the runtime
# FROM nginx:alpine

# # Copy the build output to the Nginx html directory
# COPY --from=build /web/build /usr/share/nginx/html

# # Expose port 80
# EXPOSE 80

# # Start Nginx
# CMD ["nginx", "-g", "daemon off;"]






#workes!!!!
FROM node:18.12.1-alpine 

WORKDIR /web

COPY package*.json ./

RUN npm install

COPY . .

# Set the NODE_OPTIONS environment variable
ENV NODE_OPTIONS=--openssl-legacy-provider

EXPOSE 3000

CMD ["npm", "start"]


